package com.grant;

import javax.swing.*;
import java.awt.*;

public class View extends JFrame {
    private JPanel mainPanel;
    private JTextArea textAreaConsole;
    private JButton buttonChoiceFolder;
    private JButton consoleClearButton;
    private JTextField textFieldSearch;
    private JButton processingButton;
    private JButton cancelChoiceButton;
    private JMenuItem JMenuItemExit;
    private JMenuItem JMenuItemOpenDir;
    private JTextField textFieldPath;
    private JMenuItem AboutProg;
    private JTextField textFieldReplace;
    private JMenuItem help;
    private JMenuItem ListOfChanges;
    private JTabbedPane tabbedPane;
    private JPanel Replace;
    private JPanel Add;
    private JTextField textFieldAdd;
    private JButton buttonOpenDir;

    // Constructor
    public View() {
    }

    // Getters and Setters

    public JTextArea getTextAreaConsole() {
        return textAreaConsole;
    }

    public JTextField getTextFieldSearch() {
        return textFieldSearch;
    }

    public JTextField getTextFieldPath() {
        return textFieldPath;
    }

    public JTextField getTextFieldReplace() {
        return textFieldReplace;
    }

    public JButton getButtonChoiceFolder() {
        return buttonChoiceFolder;
    }

    public JButton getConsoleClearButton() {
        return consoleClearButton;
    }

    public JButton getProcessingButton() {
        return processingButton;
    }

    public JButton getCancelChoiceButton() {
        return cancelChoiceButton;
    }

    public JMenuItem getJMenuItemExit() {
        return JMenuItemExit;
    }

    public JMenuItem getJMenuItemOpenDir() {
        return JMenuItemOpenDir;
    }

    public JMenuItem getAboutProg() {
        return AboutProg;
    }

    public JMenuItem getHelp() {
        return help;
    }

    public JMenuItem getListOfChanges() {
        return ListOfChanges;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public JTextField getTextFieldAdd() {
        return textFieldAdd;
    }

    public JButton getButtonOpenDir() {
        return buttonOpenDir;
    }

    public void init() {
        setSize(650, 500);
        initSystemLookAndFeel();
        setContentPane(getMainPanel());
        // Приложение завершит свою работу при закрытии GUI интерфейса
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Отображение по центру
        setTitle("Пакетное переименование файлов v0.3c");
        setResizable(false);
        // Устанавливаем иконку
        try {
            setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        } catch (Exception e) {
            e.printStackTrace();
        }
        setVisible(true);
        pack();
        // Делаем фрейм видимым
    }

    public void initSystemLookAndFeel() {
        try {
            String systemLookAndFeelClassName = UIManager.getSystemLookAndFeelClassName();
            // for Windows: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
            //System.out.println(systemLookAndFeelClassName); // Текущий LookAndFeel;
            UIManager.setLookAndFeel(systemLookAndFeelClassName); // устанавливаем LookAndFeel
        } catch (UnsupportedLookAndFeelException e) {
            System.err.println("Can't use the specified look and feel on this platform.");
        } catch (Exception e) {
            System.err.println("Couldn't get specified look and feel, for some reason.");
        }
    }

    public void showMessageErrorAdd() {
        JOptionPane.showMessageDialog(this, "В строке \"Добавить\" имеются недопустимые символы", "Ошибка", JOptionPane.ERROR_MESSAGE);
    }

    public void showMessageErrorReplace() {
        JOptionPane.showMessageDialog(this, "В строке \"Заменить\" имеются недопустимые символы", "Ошибка", JOptionPane.ERROR_MESSAGE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        mainPanel.add(panel1, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Вывод информации");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 6, 0, 0);
        panel1.add(label1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMinimumSize(new Dimension(400, 200));
        scrollPane1.setPreferredSize(new Dimension(400, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 6, 0, 6);
        panel1.add(scrollPane1, gbc);
        textAreaConsole = new JTextArea();
        textAreaConsole.setAutoscrolls(true);
        textAreaConsole.setBackground(new Color(-1314561));
        textAreaConsole.setEditable(false);
        scrollPane1.setViewportView(textAreaConsole);
        textFieldPath = new JTextField();
        textFieldPath.setEditable(false);
        textFieldPath.setPreferredSize(new Dimension(450, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 0);
        panel1.add(textFieldPath, gbc);
        buttonChoiceFolder = new JButton();
        buttonChoiceFolder.setIconTextGap(4);
        buttonChoiceFolder.setText("Выбор директории");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        panel1.add(buttonChoiceFolder, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Текущая директория");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(6, 6, 0, 0);
        panel1.add(label2, gbc);
        tabbedPane = new JTabbedPane();
        tabbedPane.setTabPlacement(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 6, 6, 0);
        panel1.add(tabbedPane, gbc);
        Replace = new JPanel();
        Replace.setLayout(new GridBagLayout());
        tabbedPane.addTab("Замена", Replace);
        textFieldReplace = new JTextField();
        textFieldReplace.setMinimumSize(new Dimension(49, 25));
        textFieldReplace.setPreferredSize(new Dimension(430, 25));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 6, 0, 6);
        Replace.add(textFieldReplace, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Заменить ...");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 6, 0, 0);
        Replace.add(label3, gbc);
        textFieldSearch = new JTextField();
        textFieldSearch.setMinimumSize(new Dimension(49, 25));
        textFieldSearch.setPreferredSize(new Dimension(430, 25));
        textFieldSearch.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 6, 0, 6);
        Replace.add(textFieldSearch, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Найти ...");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 6, 0, 0);
        Replace.add(label4, gbc);
        Add = new JPanel();
        Add.setLayout(new GridBagLayout());
        Add.setEnabled(true);
        tabbedPane.addTab("Добавить", Add);
        textFieldAdd = new JTextField();
        textFieldAdd.setMinimumSize(new Dimension(49, 25));
        textFieldAdd.setPreferredSize(new Dimension(430, 25));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        Add.add(textFieldAdd, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Добавление введеного текста в начало названия файлов и директорий");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 6, 0, 6);
        Add.add(label5, gbc);
        processingButton = new JButton();
        processingButton.setText("Переименовать");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        panel1.add(processingButton, gbc);
        buttonOpenDir = new JButton();
        buttonOpenDir.setText("Открыть директорию");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        panel1.add(buttonOpenDir, gbc);
        cancelChoiceButton = new JButton();
        cancelChoiceButton.setText("Отменить выбор");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        panel1.add(cancelChoiceButton, gbc);
        consoleClearButton = new JButton();
        consoleClearButton.setText("Очистить консоль");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(6, 6, 6, 6);
        panel1.add(consoleClearButton, gbc);
        final JMenuBar menuBar1 = new JMenuBar();
        menuBar1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 0));
        mainPanel.add(menuBar1, BorderLayout.NORTH);
        final JMenu menu1 = new JMenu();
        menu1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        menu1.setText("Файл");
        menuBar1.add(menu1);
        JMenuItemOpenDir = new JMenuItem();
        JMenuItemOpenDir.setLayout(new BorderLayout(0, 0));
        JMenuItemOpenDir.setInheritsPopupMenu(false);
        JMenuItemOpenDir.setText("Выбор директории");
        menu1.add(JMenuItemOpenDir);
        JMenuItemExit = new JMenuItem();
        JMenuItemExit.setLayout(new BorderLayout(0, 0));
        JMenuItemExit.setText("Выход");
        menu1.add(JMenuItemExit);
        final JMenu menu2 = new JMenu();
        menu2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        menu2.setText("Справка");
        menuBar1.add(menu2);
        help = new JMenuItem();
        help.setLayout(new BorderLayout(0, 0));
        help.setText("Помощь");
        menu2.add(help);
        ListOfChanges = new JMenuItem();
        ListOfChanges.setLayout(new BorderLayout(0, 0));
        ListOfChanges.setText("Список изменений");
        menu2.add(ListOfChanges);
        AboutProg = new JMenuItem();
        AboutProg.setLayout(new BorderLayout(0, 0));
        AboutProg.setText("О программе");
        menu2.add(AboutProg);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}


